# Default parameter values.
parameters:
  dependsOn: []
  deploymentName:
  environment: 'Dev' 
  terraformVersion: 'latest'
  artifactSuffix: $(Build.BuildNumber)
  sp_client_id:
  sp_client_secret:
  subscription_id:
  tenant_id:
  terraformConfigPath: tf-deploy
  tfvarsPath: ../environments/Dev/environment.tfvars
  backendPath: ../environments/Dev/backend.tf
  buildType: current
  downloadType: single
  downloadPath: '$(System.ArtifactsDirectory)'

stages:
- stage: 'TerraformDeploy_${{parameters.environment }}_${{ parameters.deploymentName }}'
  dependsOn: ${{ parameters.dependsOn }}
  jobs:
  - deployment: 'TerraformDeploy'
    displayName: 'Terraform apply ${{parameters.environment }}_${{ parameters.deploymentName }}'
    environment: ${{ parameters.environment }}
    strategy: 
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            displayName: "check directory"
            inputs:
              workingDirectory: '../${{ parameters.environment }}-${{ parameters.artifactSuffix }}/${{ parameters.terraformConfigPath }}'
              script: |
                pwd
                ls
          - task: TerraformInstaller@0
            displayName: 'install Terraform'
            inputs:
              workingDirectory: '${{ parameters.workingDirectory }}'
              terraformVersion: ${{ parameters.terraformVersion }}

          - task: CmdLine@2
            displayName: "Initialise Terraform deployment"
            env:
              ARM_CLIENT_ID:       ${{ parameters.sp_client_id }}
              ARM_CLIENT_SECRET:   ${{ parameters.sp_client_secret }}
              ARM_SUBSCRIPTION_ID: ${{ parameters.subscription_id }}
              ARM_TENANT_ID:       ${{ parameters.tenant_id }}
            inputs:
              workingDirectory: '../${{ parameters.environment }}-${{ parameters.artifactSuffix }}/${{ parameters.terraformConfigPath }}'
              script: terraform init -var-file=${{ parameters.tfvarsPath }} -backend-config=${{ parameters.backendPath }}      

          - task: CmdLine@2
            displayName: "Deploy configuration described in the tfplan file."
            env:
              ARM_CLIENT_ID:       ${{ parameters.sp_client_id }}
              ARM_CLIENT_SECRET:   ${{ parameters.sp_client_secret }}
              ARM_SUBSCRIPTION_ID: ${{ parameters.subscription_id }}
              ARM_TENANT_ID:       ${{ parameters.tenant_id }}
            inputs:
              workingDirectory: '../${{ parameters.environment }}-${{ parameters.artifactSuffix }}/${{ parameters.terraformConfigPath }}'
              script: |
                pwd
                ls
                terraform apply ${{ parameters.environment }}-${{ parameters.deploymentName }}-$(Build.BuildNumber).tfplan