# Default parameter values.
parameters:
  dependsOn: []
  environment: 'Dev'
  terraformVersion: 'latest'
  workingDirectory: 'tf-deploy'
  knownHosts:
  sshPublicKey:
  sshPassphrase:
  sshSecureFile:
  sp_client_id:
  sp_client_secret:
  subscription_id:
  tenant_id:
  tfvarsPath: ../environments/Dev/environment.tfvars
  backendPath: ../environments/Dev/backend.tf

stages:
- stage: 'TerraformValidate_$(Build.SourceVersion)'
  dependsOn: ${{ parameters.dependsOn }}
  jobs:
  - job: TerraformPlan
    continueOnError: false
    steps:
#    - task: InstallSSHKey@0
#      inputs:
#        knownHostsEntry: ${{ parameters.knownHosts }}
#        sshPublicKey: ${{ parameters.sshPublicKey }}
#        sshPassphrase: ${{ parameters.sshPassphrase }}
#        sshKeySecureFile: ${{ parameters.sshSecureFile }}

    - task: TerraformInstaller@0
      displayName: 'install Terraform'
      inputs:
        workingDirectory: '${{ parameters.workingDirectory }}'
        terraformVersion: ${{ parameters.terraformVersion }}

    - task: CmdLine@2
      displayName: "Initialise Terraform deployment"
      env:
        ARM_CLIENT_ID:       ${{ parameters.sp_client_id }}
        ARM_CLIENT_SECRET:   ${{ parameters.sp_client_secret }}
        ARM_SUBSCRIPTION_ID: ${{ parameters.subscription_id }}
        ARM_TENANT_ID:       ${{ parameters.tenant_id }}
      inputs:
          workingDirectory: ${{ parameters.workingDirectory }}
          script: |
            terraform init -var-file=${{ parameters.tfvarsPath }} -backend-config=${{ parameters.backendPath }}

    - task: CmdLine@2 # tfsec install
      displayName: "Install `tfsec`"
      inputs:
        script: |
          choco install tfsec

    - task: CmdLine@2 # tfsec install
      displayName: "Install `tfsec`"
      inputs:
        workingDirectory: ${{ parameters.workingDirectory }}
        script: |
          tfsec

#    - task: TerraformCLI@0
#      name: TerraformPlan
#      env:
#        ARM_CLIENT_ID:       ${{ parameters.sp_client_id }}
#        ARM_CLIENT_SECRET:   ${{ parameters.sp_client_secret }}
#        ARM_SUBSCRIPTION_ID: ${{ parameters.subscription_id }}
#        ARM_TENANT_ID:       ${{ parameters.tenant_id }}
#      inputs:
#        command: 'plan'
#        workingDirectory: ${{ parameters.workingDirectory }}
#        commandOptions: '-var-file=${{ parameters.tfvarsPath }} -out=${{ parameters.environment }}-${{ parameters.deploymentName }}-$(Build.BuildNumber).tfplan -compact-warnings -detailed-exitcode'
#        publishPlanResults: '${{ parameters.environment }}-${{ parameters.deploymentName }}-$(Build.BuildNumber)-plan'